# Generated by Django 4.2.4 on 2023-09-05 09:37

from django.db import migrations, models
import django.db.models.deletion
import school.teacher.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0001_initial"),
        ("cycle", "0001_initial"),
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teachername", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phoneno",
                    models.CharField(
                        max_length=20,
                        validators=[school.teacher.models.validate_phone_number],
                    ),
                ),
                ("subject_taught", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField()),
                ("address", models.TextField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.person",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Teachers",
            },
        ),
        migrations.CreateModel(
            name="TeachersPerCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coursespercycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.coursespercycle",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cycle.cycle"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Teachers per Course",
                "unique_together": {("coursespercycle", "cycle", "teacher")},
            },
        ),
    ]
