# Generated by Django 4.2.4 on 2023-08-27 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_coursespercycle_start_before_end"),
        ("teacher", "0002_alter_teacher_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherspercourse",
            name="coursespercycle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.coursespercycle",
            ),
        ),
    ]
