# Generated by Django 4.2.4 on 2023-09-18 16:57

from django.db import migrations, models
import school.teacher.models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0002_teacher_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="phoneno",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[school.teacher.models.validate_phone_number],
            ),
        ),
    ]
