# Generated by Django 4.2.4 on 2023-08-27 10:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0004_remove_course_teachers"),
        ("cycle", "0002_alter_cycle_options"),
        ("teacher", "0003_alter_teacherspercourse_coursespercycle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="courses",
        ),
        migrations.AlterUniqueTogether(
            name="teacherspercourse",
            unique_together={("coursespercycle", "cycle", "teacher")},
        ),
        migrations.RemoveField(
            model_name="teacherspercourse",
            name="course",
        ),
    ]
