# Generated by Django 4.2.4 on 2023-08-27 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dashboard", "0001_initial"),
        ("course", "0001_initial"),
        ("attendance", "0002_initial"),
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrollmentdate", models.DateField()),
                ("cancelled", models.BooleanField(default=False)),
                ("cancellationreason", models.TextField()),
                (
                    "course_per_cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.coursespercycle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("studentname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("birthdate", models.DateField()),
                ("phoneno", models.CharField(max_length=20)),
                ("address", models.TextField()),
                (
                    "classes",
                    models.ManyToManyField(
                        through="attendance.Attendance", to="classes.class"
                    ),
                ),
                (
                    "courses_per_cycle",
                    models.ManyToManyField(
                        through="student.Enrollment", to="course.coursespercycle"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.person",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="student.student"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["phoneno"], name="student_stu_phoneno_d8acaf_idx"
            ),
        ),
    ]
