# Generated by Django 4.2.4 on 2023-08-27 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrollment",
            options={"verbose_name_plural": "Enrollments"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name_plural": "Students"},
        ),
    ]
