# Generated by Django 4.2.4 on 2023-08-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_alter_enrollment_options_alter_student_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="enrollmentdate",
            field=models.DateField(null=True),
        ),
    ]
