# Generated by Django 4.2.4 on 2023-09-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_alter_enrollment_cancellationreason"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="password",
            field=models.CharField(default="studentpass123", max_length=100),
        ),
    ]
