# Generated by Django 4.2.4 on 2023-09-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0003_student_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="phoneno",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
