# Generated by Django 4.2.4 on 2023-08-30 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cycle", "0001_initial"),
        ("student", "0001_initial"),
        ("attendance", "0001_initial"),
        ("classes", "0001_initial"),
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="class_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="classes.class"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.course"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cycle.cycle"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="student.student"
            ),
        ),
    ]
