# Generated by Django 4.2.4 on 2023-09-16 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0007_alter_attendance_timearrive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="timearrive",
            field=models.TimeField(default=datetime.time(6, 39, 36, 765086)),
        ),
    ]
