# Generated by Django 3.0.6 on 2023-09-28 08:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_auto_20230927_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timearrive',
            field=models.TimeField(default=datetime.datetime(2023, 9, 28, 8, 15, 38, 169060, tzinfo=utc)),
        ),
    ]
