# Generated by Django 4.2.4 on 2023-09-16 06:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classes", "0004_alter_class_classtitle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lesson_number", models.PositiveIntegerField()),
                ("lesson_name", models.CharField(max_length=255)),
                (
                    "verse_to_memorize",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "chapters_to_read",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="lesson_pdfs/"),
                ),
                (
                    "class_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="classes.class",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        upload_to="lesson_pdfs/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf",
                        to="bible_study.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson PDF",
                "verbose_name_plural": "Lesson PDFs",
            },
        ),
    ]
