# Generated by Django 4.2.4 on 2023-09-16 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bible_study", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="pdf_file",
        ),
    ]
