# Generated by Django 3.0.6 on 2023-09-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible_study', '0002_remove_lesson_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lessonpdf',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
