# Generated by Django 4.2.4 on 2023-09-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("classno", models.IntegerField()),
                ("classtitle", models.CharField(max_length=100)),
                ("classdate", models.DateField()),
                ("starttime", models.TimeField()),
                ("endtime", models.TimeField()),
            ],
            options={
                "ordering": ["classdate", "starttime"],
            },
        ),
    ]
