# Generated by Django 4.2.4 on 2023-08-27 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("student", "0001_initial"),
        ("course", "0001_initial"),
        ("attendance", "0003_initial"),
        ("cycle", "0001_initial"),
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.course"
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="coursespercycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.coursespercycle"
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cycle.cycle"
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="students",
            field=models.ManyToManyField(
                through="attendance.Attendance", to="student.student"
            ),
        ),
    ]
