# Generated by Django 4.2.4 on 2023-08-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        ("student", "0001_initial"),
        ("attendance", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="students",
            field=models.ManyToManyField(
                through="attendance.Attendance", to="student.student"
            ),
        ),
    ]
