# Generated by Django 4.2.4 on 2023-09-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="classtitle",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
