# Generated by Django 4.2.4 on 2023-09-05 09:37

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import school.assignments.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "due_date",
                    models.DateField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=datetime.date(2023, 9, 5)
                            )
                        ]
                    ),
                ),
                ("description2", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Assignments",
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "submission_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=django.utils.timezone.now
                            )
                        ],
                    ),
                ),
                (
                    "file_upload",
                    models.FileField(
                        upload_to="submissions/",
                        validators=[school.assignments.models.validate_submission_file],
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assignments.assignment",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Submissions",
            },
        ),
    ]
