# Generated by Django 4.2.4 on 2023-09-05 06:03

import datetime
import django.core.validators
from django.db import migrations, models
import school.assignments.models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0004_alter_assignment_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="due_date",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2023, 9, 5)
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="file_upload",
            field=models.FileField(
                upload_to="submissions/",
                validators=[school.assignments.models.validate_submission_file],
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submission_date",
            field=models.DateTimeField(
                auto_now_add=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.datetime(
                            2023, 9, 5, 6, 3, 54, 823072, tzinfo=datetime.timezone.utc
                        )
                    )
                ],
            ),
        ),
    ]
