# Generated by Django 4.2.4 on 2023-09-11 06:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0005_alter_assignment_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="due_date",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2023, 9, 11)
                    )
                ]
            ),
        ),
    ]
