# Generated by Django 4.2.4 on 2023-09-05 07:11

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0011_alter_submission_submission_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="submission_date",
            field=models.DateTimeField(
                auto_now_add=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.datetime(
                            2023, 9, 5, 7, 11, 52, 696074, tzinfo=datetime.timezone.utc
                        )
                    )
                ],
            ),
        ),
    ]
