# Generated by Django 4.2.4 on 2023-09-15 06:25

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0014_alter_assignment_due_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="due_date",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2023, 9, 15)
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submission_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2023, 9, 15)
                    )
                ],
            ),
        ),
    ]
