# Generated by Django 4.2.4 on 2023-09-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exames", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="agenda",
            field=models.TextField(max_length=200),
        ),
    ]
