# Generated by Django 4.2.4 on 2023-08-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0001_initial"),
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="teachers",
            field=models.ManyToManyField(
                through="teacher.TeachersPerCourse", to="teacher.teacher"
            ),
        ),
    ]
