# Generated by Django 4.2.4 on 2023-09-06 06:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name_plural": "courses"},
        ),
    ]
