# Generated by Django 4.2.4 on 2023-08-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="coursespercycle",
            constraint=models.CheckConstraint(
                check=models.Q(("coursestartdate__lte", models.F("courseenddate"))),
                name="start_before_end",
            ),
        ),
    ]
