# Generated by Django 4.2.4 on 2023-08-27 10:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_coursespercycle_start_before_end"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="teachers",
        ),
    ]
