# Generated by Django 4.2.4 on 2023-08-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cycledescription", models.TextField()),
                ("cyclestartdate", models.DateField()),
                ("cycleenddate", models.DateField()),
                ("vacationstartdate", models.DateField()),
                ("vacationenddate", models.DateField()),
            ],
            options={
                "ordering": ["cyclestartdate"],
            },
        ),
    ]
