# Generated by Django 3.0.6 on 2023-09-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
